[platformio]
globallib_dir = ../../lib
src_dir = .

[env]
platform = espressif32@6.3.0
framework = arduino
upload_speed =  921600
monitor_speed = 115200
monitor_filters = default, esp32_exception_decoder

[env:t-camera-sim]
extends = env
board = esp32s3box
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_TTGO_T_CAM_SIM

; บังคับให้ค้นหาไฟล์ Header ที่ซ้อนกันอยู่ลึกๆ (แก้ปัญหาหา flatbuffers ไม่เจอ)
lib_ldf_mode = deep

lib_deps = 
    ; ใช้ไลบรารีนี้แทน จะเสถียรกับ ESP32 บน PlatformIO มากที่สุด
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0

lib_ignore = 
    TFT_eSPI
    ArduinoHttpClient

board_build.partitions = default_16MB.csv